<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\Expr;

/**
 * BedRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BedRoomRepository extends \Doctrine\ORM\EntityRepository
{

    public function search($name, $location, $startDate, $endDate)
    {
        $stmt = $this->getEntityManager()->createQueryBuilder()
                    ->select(array('u', 'h', 'l'))
                    ->from('AppBundle:BedRoom', 'u')
                    ->join('u.hotel', 'h')
                    ->join('h.location', 'l');

        if(null !== $name) {
            $stmt->andWhere("h.name LIKE :name");
            $stmt->setParameter("name", "%$name%");
        }

        if(null !== $location) {

            $stmt->andWhere($stmt->expr()->orX(
                $stmt->expr()->like('l.city', ':location'),
                $stmt->expr()->like('l.street', ':location'),
                $stmt->expr()->like('l.zipcode', ':location')
                ));

            $stmt->setParameter("location", "%$location%");
        }


        return $stmt->getQuery()->getResult();

    }
}
