<?php

namespace AppBundle\Repository;

/**
 * BedRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BedRoomRepository extends \Doctrine\ORM\EntityRepository
{

    public function search($name, $location, $startDate, $endDate)
    {
        $stmt = $this->getEntityManager()->createQueryBuilder()
                    ->select(array('u', 'h'))
                    ->from('AppBundle:BedRoom', 'u')
                    ->join('u.hotel', 'h');

        if(null !== $name) {
            $stmt->andWhere("h.name LIKE :name ");
            $stmt->setParameter("name", "%$name%");
        }

        if(null !== $location) {
            $stmt->andWhere('u.hotel.location.all LIKE :location');
            $stmt->setParameter("location", $location);
        }


        return $stmt->getQuery()->getResult();

    }
}
