<?php

namespace AppBundle\Repository;

/**
 * BedRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BedRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
