easy_admin:
  entities:
    - AppBundle\Entity\Hotel
    - AppBundle\Entity\Location
    - AppBundle\Entity\BedRoom
    - AppBundle\Entity\Booking
    - AppBundle\Entity\RoomType
    - AppBundle\Entity\User\Client
    - AppBundle\Entity\User\Responsible