# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.padding_between_booking:
        class: AppBundle\Validator\Contraints\PaddingBetweenBookingsValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
          - { name: validator.constraint_validator }
